"""empty message

Revision ID: 099215d6f3c1
Revises: 
Create Date: 2018-05-02 23:16:30.091944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099215d6f3c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    # ### end Alembic commands ###
